repo:
  - dir: C:\Users\zhshc\Desktop\gitup-test
    branch: origin/master
    mode: ontime
    time: "0 0 */1 * *"

  - dir: C:\Users\zhshc\Desktop\gituptest
    branch: origin/master
    mode: ontime
    time: "0 0 */1 * *"