listen: 0.0.0.0:8000
repo:
  - dir: C:\Users\zhshc\Desktop\gitup-test
    branch: origin/master
    mode: ontime
    time: "0 0 */1 * *"

  - dir: C:\Users\zhshc\Desktop\gitup-test
    branch: origin/master
    mode: webhook
    time: "0 0 */1 * *"